### ISSUE TITLE
AD to BS conversion

### ISSUE THREAD

**Issue by developerRojina** [xyznaveen/pal#1]
Is there any function to convert AD to BS and vice versa?

**Comment by xyznaveen** [comment]
Yes there is please take a look at [this](https://github.com/xyznaveen/pal/blob/master/ghadi/src/main/java/np/com/naveenniraula/ghadi/data/GhadiResult.kt). Also you should look at classes inside [this package](https://github.com/xyznaveen/pal/tree/master/ghadi/src/main/java/np/com/naveenniraula/ghadi/miti).

**Comment by developerRojina** [comment]
Hello @xyznaveen  First of all thank you for your very fast reply and thank you for your effort making this library. 
 I tried converting today date to nepali date using the function:

fun getMonthAndYear():String{
   val mittiDate = np.com.naveenniraula.ghadi.miti.Date(Calendar.getInstance())
   val date = DateUtils.getNepaliDate(mittiDate)
   return  date.readableAdDate
}
But it returned the date: MAY 18, 2078 
Am I doing something wrong? Can you please help me out?

**Comment by xyznaveen** [comment]
Please do something like this:

```
    private fun getToday():String {
        val nepali = np.com.naveenniraula.ghadi.miti.Date(Calendar.getInstance()).convertToNepali()
        val day = nepali.day
        val month = DateUtils.getMonthName(nepali.month)
        val year = nepali.year
        val today = "$day $month, $year"
        println("today is: $today")
        return today
    }
```

Hope this helps.

Also I have not updated this project since a year. Will do so if I find spare time.

**Comment by developerRojina** [comment]
Hello @xyznaveen  I tried this and got the result  :
18 Bhadra 2078

The day seems to be wrong. Do I need to do something with the day too?

**Comment by xyznaveen** [comment]
No you don't need to do anything.

```
private fun getToday():String {
    
    // get the date from calendar instance 
    // val nepali = np.com.naveenniraula.ghadi.miti.Date(Calendar.getInstance()).convertToNepali()
    
    // or directly pass in the date 
    // year  -> 2021 ( current ) 
    // month -> 9 ( september )
    // day   -> 6 ( today )
    // feel free to pass in anything you want 
    val nepali = np.com.naveenniraula.ghadi.miti.Date(2021, 9, 6).convertToNepali()
    
    val day = nepali.day
    val month = DateUtils.getMonthName(nepali.month)
    val year = nepali.year
    val today = "$day $month, $year"
    println("today is: $today")
    return today
}
```

The above method will output `today is: 21 भाद्र, 2078`. 

If still there is issue please use the latest commit version

`implementation 'com.github.xyznaveen:pal:807b67c758'`

See [here](https://jitpack.io/#xyznaveen/pal/807b67c758).

**Comment by developerRojina** [comment]
Thankyout @xyznaveen . It worked fine.

**Comment by developerRojina** [comment]
Hello @xyznaveen  Sorry to bother you again. Can we use date picker like material date picker in this library? I didn't found any documentation on that

**Comment by developerRojina** [comment]
Hello @xyznaveen  sorry to bother you again. I used the nepali date picker:

`
fun Fragment.showNepaliDatePicker(){
    Pal.Builder(childFragmentManager)
        .fromEnglish(System.currentTimeMillis())
        .setBackgroundColor(Color.parseColor("#0098DA"))
        .setForegroundColor(ContextCompat.getColor(requireContext(), android.R.color.white))
        .withCallback(object : DatePickCompleteListener {
            override fun onDateSelectionComplete(result: GhadiResult) {
                

            }

            override fun onDateSelectionCancelled(result: GhadiResult) {

            }
        }).build().show(childFragmentManager, "tag")

}

`

Right now the user can toggle between Ad and Bs dates
Is there any method to allow the user the selection of bs date only?

**Comment by xyznaveen** [comment]
No, you cannot only display one type of calendar with. There is no option to disable one or the other.
